name: Backend Deploy to EC2

on:
  push:
    branches: [ main ]
    paths: [ 'backend/**' ]  # Sirf backend changes pe

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Deploy to EC2
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_KEY }}
        script: |
          cd ~/backend
          # Stop old
          docker stop todo-backend my-mongo-db || true
          docker rm todo-backend my-mongo-db || true
          # Mongo
          docker run -d --name my-mongo-db -p 27017:27017 --cpus=1 --memory=512m \
            -v ~/mongo-data:/data/db \
            -e MONGO_INITDB_ROOT_USERNAME=admin \
            -e MONGO_INITDB_ROOT_PASSWORD=pass123 \
            --restart unless-stopped \
            mongo:latest
          sleep 30
          docker logs my-mongo-db
          # Backend
          docker build -t todo-backend:latest .
          docker run -d \
            --name todo-backend \
            -p 8001:8001 \
            --cpus=1 --memory=512m \
            --link my-mongo-db:mongo \
            -e MONGO_URI="mongodb://admin:pass123@mongo:27017/tododb?authSource=admin" \
            -e JWT_SECRET="b9b50e55a" \
            --restart unless-stopped \
            todo-backend:latest
          docker logs todo-backend